### ISSUE TITLE
Combined numbers and words should not be count as 2 words

### ISSUE THREAD

**Issue by phena109** [byn9826/words-count#1]
For cases like "word1" or "Should be2words" they are showing count that's not following my instincts (I know my instincts doesn't mean anything, but I really found it strange)

"word1" should consider 1 word only, but it returns me 2.

"Should be2words" should be consider 2 words, but it returns me 4.

**Comment by byn9826** [comment]
> For cases like "word1" or "Should be2words" they are showing count that's not following my instincts (I know my instincts doesn't mean anything, but I really found it strange)
> 
> "word1" should consider 1 word only, but it returns me 2.
> 
> "Should be2words" should be consider 2 words, but it returns me 4.

Yes, this is a debatable topic, that's why the readme said it will use "numbers will be count as one word" as a rule.
Based on your example, I feel they should be written as "word 1" and " should be 2 words", if you read them out. As well as common scenario like S1 -> "Season One".

But yes, there are special situations like '1st', '2nd' should definitely be counted as 1 rather than 2. This regx is not that precise.

**Comment by phena109** [comment]
Thanks for your explanation. I do find this more human in some cases and should not be fully ruled out the current way, especially this library has coverage other than English. For controversial behaviours like this, we can only pass on the decision back to the user. Therefore an option is very valuable in this case. Of course that's up to you as he developer.
